import { useState } from 'react';
import { validatePrivateKey } from '../lib/jwt';
import { checkAccess } from '../lib/github';

export default function Settings({ settings, onSave }) {
  const [form, setForm] = useState(settings);
  const [keyMsg, setKeyMsg] = useState(null);
  const [ghMsg, setGhMsg] = useState(null);
  const [busy, setBusy] = useState(false);

  const set = (k) => (e) => setForm({ ...form, [k]: e.target.value });

  function save() {
    onSave(form);
    setKeyMsg({ ok: true, text: 'Saved to this browser.' });
  }

  async function testKey() {
    const err = await validatePrivateKey(form.privateKey);
    setKeyMsg(err ? { ok: false, text: err } : { ok: true, text: 'Private key is valid (RSA PKCS#8).' });
  }

  async function testGitHub() {
    setBusy(true); setGhMsg(null);
    try {
      const info = await checkAccess({ token: form.githubToken, owner: form.owner, repo: form.repo });
      setGhMsg({ ok: true, text: `Connected. Repo is ${info.private ? 'private' : 'public'}, default branch "${info.defaultBranch}".`
        + (info.private ? ' ⚠️ Private repos are NOT readable by deployed SDKs — use a public repo or GitHub Pages for the license store.' : '') });
    } catch (e) {
      setGhMsg({ ok: false, text: e.message });
    } finally {
      setBusy(false);
    }
  }

  return (
    <>
      <div className="card">
        <h2>Signing key</h2>
        <p className="muted">Generated by <span className="mono">node tools/keygen.mjs</span>. Paste the contents of
          <span className="mono"> keys/private.pem</span>. It stays in this browser and is never uploaded — it only
          signs license tokens locally.</p>
        <label>Private key (PEM)</label>
        <textarea value={form.privateKey} onChange={set('privateKey')} spellCheck={false}
          placeholder="-----BEGIN PRIVATE KEY-----&#10;...&#10;-----END PRIVATE KEY-----" rows={6} />
        <div className="btn-row">
          <button className="secondary" onClick={testKey}>Validate key</button>
        </div>
        {keyMsg && <div className={`notice ${keyMsg.ok ? 'ok' : 'err'}`}>{keyMsg.text}</div>}
      </div>

      <div className="card">
        <h2>GitHub (license store)</h2>
        <p className="muted">A fine-scoped Personal Access Token with <strong>Contents: read/write</strong> on the
          license repo. The repo must be <strong>public</strong> (or served via GitHub Pages) so deployed apps can read it.</p>
        <label>Personal Access Token</label>
        <input type="password" value={form.githubToken} onChange={set('githubToken')}
          placeholder="github_pat_..." autoComplete="off" />
        <div className="row">
          <div><label>Owner (user/org)</label><input value={form.owner} onChange={set('owner')} placeholder="your-github-username" /></div>
          <div><label>Repo</label><input value={form.repo} onChange={set('repo')} placeholder="ownerpay-licenses" /></div>
        </div>
        <div className="row">
          <div><label>Branch</label><input value={form.branch} onChange={set('branch')} placeholder="main" /></div>
          <div><label>Path prefix</label><input value={form.pathPrefix} onChange={set('pathPrefix')} placeholder="licenses" /></div>
        </div>
        <div className="btn-row">
          <button className="secondary" onClick={testGitHub} disabled={busy || !form.githubToken || !form.owner}>
            {busy ? 'Testing…' : 'Test access'}
          </button>
        </div>
        {ghMsg && <div className={`notice ${ghMsg.ok ? 'ok' : 'err'}`}>{ghMsg.text}</div>}
      </div>

      <div className="btn-row">
        <button onClick={save}>Save settings</button>
      </div>
    </>
  );
}
